fix(TBD-13991): fix hive check services lib for EMR 6.2.x (#2764)
* Revert "fix(TBD-13897): fix wrong lib with check services on EMR62x (#2714)"

This reverts commit a854af75f77f0b6a86e4c4b9a7a6b8f7c0d10842.

* fix(TBD-13991): fix hive check services lib for EMR 6.2.x

* fix CVE

* fix(TBD-14004):NoSuchMethodError when I run spark batch job with redshift components with EMR62 (#2770)

Co-authored-by: Laurent BOURGEOIS <lbourgeois@talend.com>

* typo

* remove duplicated line

Co-authored-by: build-talend-studio-ci <build-studio-ci@talend.com>
Co-authored-by: Laurent BOURGEOIS <lbourgeois@talend.com>