fix(TBD-13812): NoClassDefFoundError: org/apache/commons/collections/map/UnmodifiableMap (#2732)
* fix(TBD-13812): CDP7.1.7.0-551 dynamic distribution missing config guava-28.1-jre.jar while testing Hadoop cluster connection

* add hadoop-common

* fix hadoop configuration class not found

* use hadoop comon as base for check services in 7.3

* add guava

Co-authored-by: unknown <ametivier@talend.com>